### ISSUE TITLE
压缩包exe无法打开

### ISSUE THREAD

**Issue by GSYangjiu** [julyL/toy#1]
windows下解压后，exe无法打开，两个压缩包都试过了，windows10 64位，项目源码 npm run dev，可以正常运行

**Comment by julyL** [comment]
我电脑win10试了一下可以的，可能之前上传的有问题，可以试下这个https://github.com/julyL/toy/releases/download/untagged-f129f5ef22931720fdb9/mytoy-win32-x64.zip
